site_name: My Docs
theme:
  name: material
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: / 
      lang: en
    - name: Chinese
      link: /cn/ 
      lang: zh